/// Flutter icons IconsMore
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconsMore
///      fonts:
///       - asset: fonts/IconsMore.ttf
///
/// 
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
///
import 'package:flutter/widgets.dart';

class IconsMore {
  IconsMore._();

  static const _kFontFam = 'IconsMore';

  static const IconData tags = const IconData(0xe802, fontFamily: _kFontFam);
}
