// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import "package:firebase_core/firebase_core.dart" show FirebaseOptions;
import "package:flutter/foundation.dart"
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          "DefaultFirebaseOptions have not been configured for windows - "
          "you can reconfigure this by running the FlutterFire CLI again.",
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          "DefaultFirebaseOptions have not been configured for linux - "
          "you can reconfigure this by running the FlutterFire CLI again.",
        );
      default:
        throw UnsupportedError(
          "DefaultFirebaseOptions are not supported for this platform.",
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCagePVcxA4nn66l6dwpwkgvEyyzrLeJIk",
    appId: "1:833002801278:web:8c8c63203debe1d388702f",
    messagingSenderId: "833002801278",
    projectId: "memorare-98eee",
    authDomain: "memorare-98eee.firebaseapp.com",
    databaseURL: "https://memorare-98eee.firebaseio.com",
    storageBucket: "memorare-98eee.appspot.com",
    measurementId: "G-MRWHQ5GBXC",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyDpNniHWhLgH75U2LpFRA_2LDrFi_MwyFM",
    appId: "1:833002801278:android:6f4a4fb04965167c88702f",
    messagingSenderId: "833002801278",
    projectId: "memorare-98eee",
    databaseURL: "https://memorare-98eee.firebaseio.com",
    storageBucket: "memorare-98eee.appspot.com",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyBwnwY5Id0FFdgBARdAD8v1e8jfgHMmO5E",
    appId: "1:833002801278:ios:2ee5847e708d0d1d88702f",
    messagingSenderId: "833002801278",
    projectId: "memorare-98eee",
    databaseURL: "https://memorare-98eee.firebaseio.com",
    storageBucket: "memorare-98eee.appspot.com",
    androidClientId:
        "833002801278-1388jlc0h93fio718sn89s4409q049l1.apps.googleusercontent.com",
    iosClientId:
        "833002801278-u0g4s670ttmsfv4q2qct1uj45ftpt7ir.apps.googleusercontent.com",
    iosBundleId: "com.example.kwotes",
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyBwnwY5Id0FFdgBARdAD8v1e8jfgHMmO5E",
    appId: "1:833002801278:ios:820a43513c13d53d88702f",
    messagingSenderId: "833002801278",
    projectId: "memorare-98eee",
    databaseURL: "https://memorare-98eee.firebaseio.com",
    storageBucket: "memorare-98eee.appspot.com",
    androidClientId:
        "833002801278-1388jlc0h93fio718sn89s4409q049l1.apps.googleusercontent.com",
    iosClientId:
        "833002801278-spne6vo34ug0vo3rtkt2u3cjjtv4deo8.apps.googleusercontent.com",
    iosBundleId: "com.example.kwotes.RunnerTests",
  );
}
